#!/usr/bin/python3
from sys import argv
from math import sqrt


def factor():
    with open(argv[1]) as p:
        for line in p:
            num = int(line)
            print("{:d}=".format(num), end="")
            if num % 2 == 0:
                print("{}*2".format(num//2))
                continue
            sqn = int(sqrt(num))
            if sqn % 2 == 0:
                sqn += 1
            for q in range(3, sqn + 1, 2):
                if num % q == 0:
                    print("{}*{}".format(q, num//q))
                    break
            if num % q != 0:
                print("{}={}*1".format(num, num))

    factor()
